#!/bin/bash

path=`pwd`
${path}/Super/SuperServer -t 2 -d -f script/Super.lua
sleep 0.1
${path}/Record/RecordServer -t 2 -d -f script/login.lua
sleep 0.1
${path}/Session/SessionServer -t 2 -d -f script/login.lua
