-- do not edit this file manully

require "script/CommandMap"

local m = CommandMap.m
local M = CommandMap.M
local R = CommandMap.Register

if Cmd == nil then Cmd = {} end

Cmd.stAttackMagicUserCmd = 1737584310

R(Cmd.stAttackMagicUserCmd,"Cmd.stAttackMagicUserCmd")

