-- do not edit this file manully

require "script/CommandMap"

local m = CommandMap.m
local M = CommandMap.M
local R = CommandMap.Register

if Gate == nil then Gate = {} end

Gate.stUserVerifyVerCmd = 1503526752
Gate.stPasswdLogonUserCmd = 1204907888
Gate.stServerReturnLoginFailedCmd = 1476770246
Gate.SelectUserInfo = 1725277454
Gate.stUserInfoUserCmd = 1740466449
Gate.stCheckNameSelectUserCmd = 2105189365
Gate.stCreateSelectUserCmd = 926968561
Gate.stLoginSelectUserCmd = 2063957165

R(Gate.stUserVerifyVerCmd,"Gate.stUserVerifyVerCmd")
R(Gate.stPasswdLogonUserCmd,"Gate.stPasswdLogonUserCmd")
R(Gate.stServerReturnLoginFailedCmd,"Gate.stServerReturnLoginFailedCmd")
R(Gate.SelectUserInfo,"Gate.SelectUserInfo")
R(Gate.stUserInfoUserCmd,"Gate.stUserInfoUserCmd")
R(Gate.stCheckNameSelectUserCmd,"Gate.stCheckNameSelectUserCmd")
R(Gate.stCreateSelectUserCmd,"Gate.stCreateSelectUserCmd")
R(Gate.stLoginSelectUserCmd,"Gate.stLoginSelectUserCmd")

