-- do not edit this file manully

require "script/CommandMap"

local m = CommandMap.m
local M = CommandMap.M
local R = CommandMap.Register

if SceneCmd == nil then SceneCmd = {} end

SceneCmd.MapIndexXY = 2077043203
SceneCmd.t_fresh_MapIndex = 712510158

R(SceneCmd.MapIndexXY,"SceneCmd.MapIndexXY")
R(SceneCmd.t_fresh_MapIndex,"SceneCmd.t_fresh_MapIndex")

