-- do not edit this file manully

require "script/CommandMap"

local m = CommandMap.m
local M = CommandMap.M
local R = CommandMap.Register

if Super == nil then Super = {} end

Super.ServerEntry = 2121707574
Super.t_Startup_Request = 1455155951
Super.t_Startup_Response = 887715398
Super.t_NewSession_Gateway = 2013117995
Super.t_RQGYList_Gateway = 1972272450
Super.t_GYList_Gateway = 1899785535

R(Super.ServerEntry,"Super.ServerEntry")
R(Super.t_Startup_Request,"Super.t_Startup_Request")
R(Super.t_Startup_Response,"Super.t_Startup_Response")
R(Super.t_NewSession_Gateway,"Super.t_NewSession_Gateway")
R(Super.t_RQGYList_Gateway,"Super.t_RQGYList_Gateway")
R(Super.t_GYList_Gateway,"Super.t_GYList_Gateway")

