-- do not edit this file manully

require "script/CommandMap"

local m = CommandMap.m
local M = CommandMap.M
local R = CommandMap.Register

if Super == nil then Super = {} end

Super.ServerEntry = 2121707574
Super.t_Startup_Request = 1455155951
Super.t_Startup_Response = 887715398
Super.stLoginToGame = 1540112462
Super.stLoginGameServerResult = 2044466912
Super.PlayerInfo = 721395520
Super.stSearchFight = 1372442858

R(Super.ServerEntry,"Super.ServerEntry")
R(Super.t_Startup_Request,"Super.t_Startup_Request")
R(Super.t_Startup_Response,"Super.t_Startup_Response")
R(Super.stLoginToGame,"Super.stLoginToGame")
R(Super.stLoginGameServerResult,"Super.stLoginGameServerResult")
R(Super.PlayerInfo,"Super.PlayerInfo")
R(Super.stSearchFight,"Super.stSearchFight")

