asan_test: asan_test.cpp
	g++ -g -std=c++11 -fsanitize=address asan_test.cpp -o asan_test

clean:
	rm asan_test

#g++ -g -O1 -std=c++11 -fsanitize=address -fno-omit-frame-pointer -fno-optimize-sibling-calls asan_test.cpp -o asan_test
